apiVersion: v1
kind: Service
metadata:
  name: olympic-games-app-service
spec:
  selector:
    app: olympic-games-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
